// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdFormCurrencyConversion.Models;

public partial class CurrencyConversionHistory
{
    public int Id { get; set; }

    public string FromCurrency { get; set; }

    public string ToCurrency { get; set; }

    public decimal InputAmount { get; set; }

    public decimal ConvertedAmount { get; set; }

    public DateTime ConversionDate { get; set; }
}