// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdFormCurrencyConversion.Models;

public partial class ExchangeRate
{
    public int Id { get; set; }

    public string CurrencyCode { get; set; }

    public string CurrencyDesc { get; set; }

    public decimal Rate { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string CurrencyCodeReference { get; set; }
}